export const Users = [
  {
    id: "#8000",
    fullName: "Li Wei Chen",
    email: "liwei.fluxpay@gmail.com",
    phone: "07073786594",
    sex: "Male",
    class: "Premium",
    progress: 2,
  },
  {
    id: "#7999",
    fullName: "Emma Thompson",
    email: "emma.fluxpay@gmail.com",
    phone: "08185659869",
    sex: "Female",
    class: "Basic",
    progress: 1,
  },
  {
    id: "#7998",
    fullName: "Adebayo Olanrewaju",
    email: "adebayo.fluxpay@gmail.com",
    phone: "09193456579",
    sex: "Male",
    class: "Premium",
    progress: 3,
  },
  {
    id: "#7997",
    fullName: "Carla Silva",
    email: "carla.fluxpay@gmail.com",
    phone: "08074849584",
    sex: "Female",
    class: "Standard",
    progress: 2,
  },
  {
    id: "#7996",
    fullName: "Hiroshi Tanaka",
    email: "hiroshi.fluxpay@gmail.com",
    phone: "09002934588",
    sex: "Male",
    class: "Premium",
    progress: 3,
  },
  {
    id: "#7995",
    fullName: "Sarah Williams",
    email: "sarah.fluxpay@gmail.com",
    phone: "07003948567",
    sex: "Female",
    class: "Standard",
    progress: 2,
  },
  {
    id: "#7994",
    fullName: "Chioma Nwachukwu",
    email: "chioma.fluxpay@gmail.com",
    phone: "09090039485",
    sex: "Female",
    class: "Basic",
    progress: 1,
  },
  {
    id: "#7993",
    fullName: "Joao Santos",
    email: "joao.fluxpay@gmail.com",
    phone: "08092384759",
    sex: "Male",
    class: "Standard",
    progress: 2,
  },
  {
    id: "#7992",
    fullName: "Mei Lin Zhang",
    email: "meilin.fluxpay@gmail.com",
    phone: "081029387402",
    sex: "Female",
    class: "Premium",
    progress: 3,
  },
  {
    id: "#7991",
    fullName: "Michael Fraser",
    email: "michael.fluxpay@gmail.com",
    phone: "07092837648",
    sex: "Male",
    class: "Basic",
    progress: 1,
  },
  {
    id: "#7990",
    fullName: "Folake Adeleke",
    email: "folake.fluxpay@gmail.com",
    phone: "07073786594",
    sex: "Female",
    class: "Standard",
    progress: 2,
  },
  {
    id: "#7989",
    fullName: "Lucas Oliveira",
    email: "lucas.fluxpay@gmail.com",
    phone: "08185659869",
    sex: "Male",
    class: "Basic",
    progress: 1,
  },
  {
    id: "#7988",
    fullName: "Yuki Nakamura",
    email: "yuki.fluxpay@gmail.com",
    phone: "09193456579",
    sex: "Female",
    class: "Premium",
    progress: 3,
  },
  {
    id: "#7987",
    fullName: "Jessica Mackenzie",
    email: "jessica.fluxpay@gmail.com",
    phone: "08074849584",
    sex: "Female",
    class: "Standard",
    progress: 2,
  },
  {
    id: "#7986",
    fullName: "Oluwaseun Ajayi",
    email: "oluwaseun.fluxpay@gmail.com",
    phone: "09002934588",
    sex: "Male",
    class: "Premium",
    progress: 3,
  },
  {
    id: "#7985",
    fullName: "Fernanda Costa",
    email: "fernanda.fluxpay@gmail.com",
    phone: "07003948567",
    sex: "Female",
    class: "Standard",
    progress: 2,
  },
  {
    id: "#7984",
    fullName: "Kenji Suzuki",
    email: "kenji.fluxpay@gmail.com",
    phone: "09090039485",
    sex: "Male",
    class: "Basic",
    progress: 1,
  },
  {
    id: "#7983",
    fullName: "Olivia Bennett",
    email: "olivia.fluxpay@gmail.com",
    phone: "08092384759",
    sex: "Female",
    class: "Standard",
    progress: 2,
  },
  {
    id: "#7982",
    fullName: "Chidimma Okonkwo",
    email: "chidimma.fluxpay@gmail.com",
    phone: "081029387402",
    sex: "Female",
    class: "Premium",
    progress: 3,
  },
  {
    id: "#7981",
    fullName: "Pedro Almeida",
    email: "pedro.fluxpay@gmail.com",
    phone: "07092837648",
    sex: "Male",
    class: "Basic",
    progress: 1,
  },
  {
    id: "#7980",
    fullName: "Seo-yeon Kim",
    email: "seoyeon.fluxpay@gmail.com",
    phone: "07073786594",
    sex: "Female",
    class: "Standard",
    progress: 2,
  },
  {
    id: "#7979",
    fullName: "Ryan MacDonald",
    email: "ryan.fluxpay@gmail.com",
    phone: "08185659869",
    sex: "Male",
    class: "Basic",
    progress: 1,
  },
  {
    id: "#7978",
    fullName: "Ngozi Eze",
    email: "ngozi.fluxpay@gmail.com",
    phone: "09193456579",
    sex: "Female",
    class: "Premium",
    progress: 3,
  },
  {
    id: "#7977",
    fullName: "Thiago Pereira",
    email: "thiago.fluxpay@gmail.com",
    phone: "08074849584",
    sex: "Male",
    class: "Standard",
    progress: 2,
  },
  {
    id: "#7976",
    fullName: "Aiko Yamamoto",
    email: "aiko.fluxpay@gmail.com",
    phone: "09002934588",
    sex: "Female",
    class: "Premium",
    progress: 3,
  },
  {
    id: "#7975",
    fullName: "Liam Campbell",
    email: "liam.fluxpay@gmail.com",
    phone: "07003948567",
    sex: "Male",
    class: "Standard",
    progress: 2,
  },
  {
    id: "#7974",
    fullName: "Bukola Adeyemi",
    email: "bukola.fluxpay@gmail.com",
    phone: "09090039485",
    sex: "Female",
    class: "Basic",
    progress: 1,
  },
  {
    id: "#7973",
    fullName: "Ana Souza",
    email: "ana.fluxpay@gmail.com",
    phone: "08092384759",
    sex: "Female",
    class: "Standard",
    progress: 2,
  },
  {
    id: "#7972",
    fullName: "Jin-ho Park",
    email: "jinho.fluxpay@gmail.com",
    phone: "081029387402",
    sex: "Male",
    class: "Premium",
    progress: 3,
  },
  {
    id: "#7971",
    fullName: "Samantha Cooper",
    email: "samantha.fluxpay@gmail.com",
    phone: "07092837648",
    sex: "Female",
    class: "Basic",
    progress: 1,
  },
];
